controller_manager:
  ros__parameters:
    update_rate: 500
    enforce_command_limits: true
    joint_state_broadcaster: {type: joint_state_broadcaster/JointStateBroadcaster}
    rm_group_controller: {type: joint_trajectory_controller/JointTrajectoryController}
    parallel_gripper_controller: {type: forward_command_controller/ForwardCommandController}
rm_group_controller:
  ros__parameters:
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6, joint_7]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    action_monitor_rate: 50.0
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.01
      joint_1: {trajectory: 0.05, goal: 0.002}
      joint_2: {trajectory: 0.05, goal: 0.002}
      joint_3: {trajectory: 0.05, goal: 0.002}
      joint_4: {trajectory: 0.05, goal: 0.002}
      joint_5: {trajectory: 0.05, goal: 0.002}
      joint_6: {trajectory: 0.05, goal: 0.002}
      joint_7: {trajectory: 0.05, goal: 0.002}
parallel_gripper_controller:
  ros__parameters:
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint
      - gripper_left_inner_knuckle_joint
      - gripper_right_inner_knuckle_joint
      - gripper_left_finger_tip_joint
      - gripper_right_finger_tip_joint
    interface_name: effort
